import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';
import {ConsumptionService,ConsumptionStore,validateConsumption} from '../src/consumption.js';
import type {ConsumptionDetails,ConsumptionHistory} from '../src/types.js';import {FakeCellar,bottle} from './helpers.js';
class Fake extends FakeCellar{
 consumeCalls:string[][]=[];records:ConsumptionHistory['records']=[];historyOffline=false;wrongDetails=false;omitRecord=false;loseResponse=false;
 async consumed(ids:string[]){if(this.historyOffline)throw Error();return structuredClone({accountId:this.accountId,records:this.records.filter(r=>ids.includes(r.id))});}
 async consume(ids:string[],details:ConsumptionDetails){
  this.consumeCalls.push(ids);for(const id of this.partial?ids.slice(0,1):ids){const b=this.bottles.find(b=>b.id===id)!;this.bottles=this.bottles.filter(b=>b.id!==id);if(!this.omitRecord)this.records.push({id,consumedId:'9'+id,wineId:b.wineId!,...details,...(this.wrongDetails?{date:'2020-01-01'}:{})});}
  if(this.loseResponse)throw Error('Lost response');
 }
}
const details={date:'2026-09-15',type:1,note:'With dinner'};
async function setup(t:any,items=[bottle('1'),bottle('2')]){const dir=await mkdtemp(join(tmpdir(),'ct-consume-'));t.after(()=>rm(dir,{recursive:true,force:true}));const cellar=new Fake(items);const store=new ConsumptionStore(dir);return {cellar,store,service:new ConsumptionService(cellar,store)};}
test('consumes selected IDs and verifies history metadata; repeat cannot consume another bottle',async t=>{const {cellar,service,store}=await setup(t);const p=await service.plan({wine_id:'100',quantity:1},details);assert.equal(cellar.consumeCalls.length,0);const r=await service.execute(p.id);assert.equal(r.status,'complete');assert.deepEqual(r.consumedIds,['1']);assert.deepEqual(cellar.bottles.map(b=>b.id),['2']);await new ConsumptionService(cellar,store).execute(p.id);assert.equal(cellar.consumeCalls.length,1);assert.deepEqual((await service.status(p.id)).observedNow.consumedIds,['1']);});
test('disappearance without a consumption record is not success',async t=>{const {cellar,service}=await setup(t);const p=await service.plan({bottle_ids:['1']},details);cellar.omitRecord=true;const r=await service.execute(p.id);assert.equal(r.status,'partial');assert.deepEqual(r.conflictIds,['1']);});
test('history with a different date is not accepted as our consumption',async t=>{const {cellar,service}=await setup(t);const p=await service.plan({bottle_ids:['1']},details);cellar.wrongDetails=true;assert.equal((await service.execute(p.id)).status,'partial');});
test('changed bottle location blocks consumption before submission',async t=>{const {cellar,service}=await setup(t);const p=await service.plan({bottle_ids:['1']},details);cellar.bottles[0].bin='99';assert.equal((await service.execute(p.id)).status,'conflict');assert.equal(cellar.consumeCalls.length,0);});
test('account switch blocks consumption',async t=>{const {cellar,service}=await setup(t);const p=await service.plan({bottle_ids:['1']},details);cellar.accountId='999';await assert.rejects(()=>service.execute(p.id),/account changed/);assert.equal(cellar.consumeCalls.length,0);});
test('expired consumption plan and interrupted running state never write',async t=>{const {cellar,service,store}=await setup(t);const p=await service.plan({bottle_ids:['1']},details);p.expiresAt=new Date(0).toISOString();await store.save(p);await assert.rejects(()=>service.execute(p.id),/expired/);p.status='running';await store.save(p);assert.equal((await service.execute(p.id)).status,'running');assert.equal(cellar.consumeCalls.length,0);});
test('lost consumption response reconciles from history',async t=>{const {cellar,service}=await setup(t);const p=await service.plan({bottle_ids:['1']},details);cellar.loseResponse=true;assert.equal((await service.execute(p.id)).status,'complete');assert.equal(cellar.consumeCalls.length,1);});
test('partial consumption stops and records precisely what remains',async t=>{const {cellar,service}=await setup(t);const p=await service.plan({bottle_ids:['1','2']},details);cellar.partial=true;const r=await service.execute(p.id);assert.equal(r.status,'partial');assert.deepEqual(r.remainingIds,['2']);await service.execute(p.id);assert.equal(cellar.consumeCalls.length,1);});
test('history outage after write is unknown and never replayed',async t=>{const {cellar,service}=await setup(t);const p=await service.plan({bottle_ids:['1']},details);const consume=cellar.consume.bind(cellar);cellar.consume=async(ids,d)=>{await consume(ids,d);cellar.historyOffline=true;};assert.equal((await service.execute(p.id)).status,'unknown');await service.execute(p.id);assert.equal(cellar.consumeCalls.length,1);});
test('large consumption batches remain bounded',async t=>{const {cellar,service}=await setup(t,Array.from({length:51},(_,i)=>bottle(String(i+1))));const p=await service.plan({wine_id:'100',quantity:51},details);assert.equal((await service.execute(p.id)).status,'complete');assert.deepEqual(cellar.consumeCalls.map(c=>c.length),[50,1]);});
test('deletion type, invalid dates and multiline notes are rejected',()=>{for(const d of [{...details,type:0},{...details,date:'2026-02-30'},{...details,date:'yesterday'},{...details,note:'line\nline'}])assert.throws(()=>validateConsumption(d));});
