import {test} from 'node:test';import assert from 'node:assert/strict';import {mkdtemp,rm} from 'node:fs/promises';import {tmpdir} from 'node:os';import {join} from 'node:path';import {runInNewContext} from 'node:vm';import {readFileSync} from 'node:fs';
import {CreationService,CreationStore,parseCreationForm,searchWines} from '../src/creation.js';import {buildRequest} from '../src/http.js';import {FakeCellar,bottle} from './helpers.js';
export const creationForm=(account='123')=>`<div id="header"><a href="user.asp?iUserOverride=${account}">Example</a></div><form id="wine_form" action="purchase.asp" method="post"><div id="wine_summary"><h2>2020 Example Wine</h2></div><input name="iWine" value="100"><input name="Action" value="Add"><input name="BinUI" value="Bulk"><input name="Quantity" value="1"><select name="Size"><option>750ml</option><option>1.5L</option></select><input name="DeliveryState" value="delivered"><input name="DeliveryState" value="pending"><input name="Location"><input name="Bin"><input name="BottleNote"><input name="StoreName"><input name="PurchaseDate"><input name="DeliveryDate"><select name="BottleCostCurrency"><option>USD</option></select><input name="BottleCost"><textarea name="PurchaseNote"></textarea></form>`;
const input={wineId:'100',quantity:2,size:'750ml',location:'Home',bin:''};
const response=(text:string)=>({status:200,url:'https://www.cellartracker.com/purchase.asp',text});
async function setup(t:any){const dir=await mkdtemp(join(tmpdir(),'ct-create-'));t.after(()=>rm(dir,{recursive:true,force:true}));const cellar=new FakeCellar([bottle('1')]);const store=new CreationStore(dir);let writes=0;const config={count:2,fail:false,readFailure:false,wrong:false,account:'123',form:creationForm()};const inventory=cellar.inventory.bind(cellar);cellar.inventory=async()=>{if(writes&&config.readFailure)throw Error();return inventory();};const service=new CreationService(cellar,{request:async r=>{if(r.kind==='creationForm')return response(config.form);if(r.kind!=='createBottles')throw Error();writes++;for(let i=0;i<config.count;i++)cellar.bottles.push({...bottle(String(i+2),config.wrong?'Other':r.details.location,r.details.bin),size:r.details.size,wineId:r.details.wineId});if(config.fail)throw Error('Lost response');return response('');}},store);return {service,cellar,store,config,writes:()=>writes};}
test('creation freezes baseline, verifies new IDs, and never replays',async t=>{const x=await setup(t);const p=await x.service.plan(input);assert.equal(x.writes(),0);assert.deepEqual((await x.service.execute(p.id)).addedIds,['2','3']);assert.equal((await x.service.execute(p.id)).status,'complete');assert.equal(x.writes(),1);assert.deepEqual((await x.service.status(p.id)).observedNow.addedIds,['2','3']);});
test('lost creation response reconciles without resubmitting',async t=>{const x=await setup(t);x.config.fail=true;const p=await x.service.plan(input);assert.equal((await x.service.execute(p.id)).status,'complete');assert.equal(x.writes(),1);});
test('inventory changed after planning blocks creation',async t=>{const x=await setup(t);const p=await x.service.plan(input);x.cellar.bottles.push(bottle('9'));assert.equal((await x.service.execute(p.id)).status,'conflict');assert.equal(x.writes(),0);});
test('account drift and unsupported sizes prevent creation',async t=>{const x=await setup(t);await assert.rejects(()=>x.service.plan({...input,size:'9L'}),/unsupported/);const p=await x.service.plan(input);x.config.form=creationForm('999');assert.equal((await x.service.execute(p.id)).status,'conflict');assert.equal(x.writes(),0);});
test('expired and running plans cannot submit',async t=>{const x=await setup(t);const p=await x.service.plan(input);p.expiresAt='2000-01-01';await x.store.save(p);await assert.rejects(()=>x.service.execute(p.id),/expired/);p.status='running';await x.store.save(p);assert.equal((await x.service.execute(p.id)).status,'running');assert.equal(x.writes(),0);});
test('partial, excess, and wrong-location creations are not complete',async t=>{for(const cfg of [{count:1},{count:3},{wrong:true}]){const x=await setup(t);Object.assign(x.config,cfg);const p=await x.service.plan(input);assert.equal((await x.service.execute(p.id)).status,'partial');await x.service.execute(p.id);assert.equal(x.writes(),1);}});
test('verification outage and no added bottles remain unknown',async t=>{for(const cfg of [{readFailure:true},{count:0}]){const x=await setup(t);Object.assign(x.config,cfg);const p=await x.service.plan(input);assert.equal((await x.service.execute(p.id)).status,'unknown');await x.service.execute(p.id);assert.equal(x.writes(),1);}});
test('creation form rejects new fields, wrong identity and changed action',()=>{assert.equal(parseCreationForm(creationForm(),'100').wine,'2020 Example Wine');for(const text of [creationForm().replace('</form>','<input name="Unexpected"></form>'),creationForm().replace('value="100"','value="101"'),creationForm().replace('value="Add"','value="Delete"')])assert.throws(()=>parseCreationForm(text,'100'),/contract changed/);});
test('direct and companion creation request contracts agree and cannot inject actions',()=>{const context:any={};runInNewContext(readFileSync('extension/protocol.js','utf8'),context);for(const req of [{kind:'searchWines',query:'Example & wine',page:2},{kind:'creationForm',wineId:'100'},{kind:'createBottles',details:{...input,location:'Café & 家'},currency:'USD'}] as const){assert.deepEqual(JSON.parse(JSON.stringify(context.CellarTrackerProtocol.build(req))),buildRequest(req));}const req:any={kind:'createBottles',details:input,currency:'USD'};for(const details of [{...input,quantity:0},{...input,quantity:241},{...input,wineId:'100&Action=Delete'},{...input,location:''}]){assert.throws(()=>buildRequest({...req,details}));assert.throws(()=>context.CellarTrackerProtocol.build({...req,details}));}const body=buildRequest(req).body!;assert.equal(new URLSearchParams(body).get('PurchaseDate'),'');assert.equal(new URLSearchParams(body).get('Action'),'Add');});
test('global search returns exact catalog IDs with pagination',async()=>{const text=creationForm()+'<a id="top_gotolink">page 1 of 2</a><table id="main_table"><tr><td><input name="iWine" value="100"></td><td class="type">Red</td><td class="name"><h3>2020 Example Wine</h3><span class="loc">Example region</span></td></tr></table>';const result=await searchWines({request:async()=>response(text)},'Example',1);assert.deepEqual(result,{wines:[{wineId:'100',wine:'2020 Example Wine',region:'Example region',type:'Red'}],page:1,pages:2});await assert.rejects(()=>searchWines({request:async()=>response('login')},'Example',1));});
test('single-page search validates wine total when pagination is omitted',async()=>{const text=creationForm()+'<span>1 Wines</span><table id="main_table"><tr><td><input name="iWine" value="100"></td><td class="name"><h3>2020 Example Wine</h3></td></tr></table>';assert.equal((await searchWines({request:async()=>response(text)},'Example',1)).pages,1);await assert.rejects(()=>searchWines({request:async()=>response(text.replace('1 Wines','2 Wines'))},'Example',1),/pagination/);});
