import {CreationService,CreationStore,searchWines} from './creation.js';
import {join} from 'node:path';
import {ConsumptionService,ConsumptionStore,consumptionTypes} from './consumption.js';
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js';
import { z } from 'zod';
import { CellarTracker } from './cellar.js';
import { MoveService } from './moves.js';
import { MoveStore } from './store.js';
import { SafeError, type Transport } from './types.js';
const label=z.string().max(40);
const selection={bottle_ids:z.array(z.string().regex(/^\d+$/)).min(1).max(1000).optional(),wine_id:z.string().regex(/^\d+$/).optional(),quantity:z.number().int().min(1).max(1000).optional(),location:label.optional(),bin:label.optional(),size:z.string().optional()};
const selectionHelp='Select bottle_ids returned by list_bottles, OR wine_id plus quantity and optional exact source location/bin/size. Quantity selection requires one source location/bin/size group and chooses ascending bottle IDs. Never infer a wine ID from its name.';

export function createMcp(transport:Transport,store:MoveStore,connected:()=>boolean,mode="browser"){
  const server=new McpServer({name:'cellartracker-write-mcp',version:'0.1.0'});
  const cellar=new CellarTracker(transport);const moves=new MoveService(cellar,store);const consumption=new ConsumptionService(cellar,new ConsumptionStore(join(store.directory,'consumption')));
  // Serialize tools so writes cannot interleave within this server.
  let tail:Promise<unknown>=Promise.resolve();
  const run=(fn:()=>Promise<unknown>)=>{const next=tail.then(async()=>{
    try{const result=await fn();return {content:[{type:'text' as const,text:JSON.stringify(result)}]};}
    catch(e){return {isError:true,content:[{type:'text' as const,text:e instanceof SafeError?e.message:'Operation failed. Inspect the local setup and operation status; do not blindly retry a write.'}]};}
  });tail=next.catch(()=>{});return next;};
  const creation=new CreationService(cellar,transport,new CreationStore(join(store.directory,'creation')));
  const read={readOnlyHint:true,destructiveHint:false,openWorldHint:true};
  server.registerTool('connection_status',{description:'Check transport availability and mode. A configured cookie file or connected browser does not prove login; list_bins verifies authentication.',inputSchema:{},annotations:read},async()=>({content:[{type:'text',text:JSON.stringify({connected:connected(),transport:mode})}]}));
  server.registerTool('list_bins',{description:'Read fresh, complete inventory and summarize exact location/bin labels and bottle counts.',inputSchema:{},annotations:read},()=>run(async()=>{
    const inventory=await cellar.inventory();const bins=new Map<string,{location:string;bin:string;count:number}>();
    for(const b of inventory.bottles){const key=JSON.stringify([b.location,b.bin]);const bin=bins.get(key)??{location:b.location,bin:b.bin,count:0};bin.count++;bins.set(key,bin);}
    return {accountId:inventory.accountId,total:inventory.bottles.length,bins:[...bins.values()]};
  }));
  server.registerTool('list_bottles',{description:'List individual bottles from fresh complete inventory, with optional exact bin/location and substring wine filters. Read every offset if all results are needed.',inputSchema:{location:label.optional(),bin:label.optional(),wine:z.string().optional(),wine_id:z.string().regex(/^\d+$/).optional(),size:z.string().optional(),offset:z.number().int().min(0).default(0),limit:z.number().int().min(1).max(100).default(50)},annotations:read},args=>run(async()=>{
    const inventory=await cellar.inventory();const bottles=inventory.bottles.filter(b=>(args.wine_id===undefined||b.wineId===BigInt(args.wine_id).toString())&&(args.size===undefined||b.size===args.size)&&(args.location===undefined||b.location===args.location)&&(args.bin===undefined||b.bin===args.bin)&&(args.wine===undefined||b.wine.toLowerCase().includes(args.wine.toLowerCase())));
    return {accountId:inventory.accountId,total:bottles.length,bottles:bottles.slice(args.offset,args.offset+args.limit)};
  }));
  server.registerTool('plan_bin_move',{description:'Prepare and persist a 15-minute move plan with exact bottle IDs. Does not modify CellarTracker. Use exact source/destination labels; omitted location is resolved only when unambiguous. Preserve location unless destination_location is explicitly requested. For a clear user-authorized move, follow immediately with execute_bin_move; no extra user confirmation is inherently required.',inputSchema:{source_bin:label,destination_bin:label,location:label.optional(),destination_location:label.optional()},annotations:{...read,readOnlyHint:false,openWorldHint:true}},a=>run(()=>moves.plan(a.source_bin,a.destination_bin,a.location,a.destination_location)));
  server.registerTool('execute_bin_move',{description:'Execute an existing user-authorized plan. Changes CellarTracker bottle locations/bins; checks current account and source membership, verifies every batch and records outcomes. Reusing an operation ID never replays writes. A partial/unknown/running result requires get_move_status and deliberate recovery, not automatic creation of a replacement plan.',inputSchema:{operation_id:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:true}},a=>run(()=>moves.execute(a.operation_id)));
  server.registerTool('plan_bottle_move',{description:'Prepare a move for selected bottles; does not modify CellarTracker. '+selectionHelp+' Preserve each bottle’s location unless destination_location is supplied. The LLM can compose these primitives for undo or reorganization using original bottle IDs; snapshot both sets before a bin swap. Follow with execute_bottle_move when authorized.',inputSchema:{...selection,destination_bin:label,destination_location:label.optional()},annotations:{...read,readOnlyHint:false}},a=>run(()=>moves.planBottles(a,a.destination_bin,a.destination_location)));
  server.registerTool('execute_bottle_move',{description:'Execute a user-authorized bottle move plan and verify exact bottle IDs. Also accepts bin move plans. Never replays an operation ID; inspect get_move_status for partial/unknown/running results.',inputSchema:{operation_id:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:true}},a=>run(()=>moves.execute(a.operation_id)));
  server.registerTool('plan_bottle_consumption',{description:'Prepare logging consumption of selected in-stock bottles. '+selectionHelp+' Supply an absolute date resolved from the user’s intended timezone. The note is a consumption note, not a published tasting note. Does not modify CellarTracker. Follow with execute_bottle_consumption for an authorized request.',inputSchema:{...selection,date:z.string().regex(/^\d{4}-\d{2}-\d{2}$/),reason:z.enum(['drank','gift','restaurant','sold_or_traded','spoiled_returned','tasted','broken','spoiled','missing','donated','family','friends_cellar','cooking','tasting_event']).default('drank'),note:z.string().max(512).default('')},annotations:{...read,readOnlyHint:false}},a=>run(()=>consumption.plan(a,{date:a.date,type:consumptionTypes[a.reason],note:a.note})));
  server.registerTool('execute_bottle_consumption',{description:'Log a user-authorized planned consumption. Removes selected bottles from current inventory and records their consumption date/reason/note. Verifies exact bottle IDs in consumption history and their absence from inventory. No permanent-delete or tasting-note publication. Repeated operation IDs never replay writes; inspect get_consumption_status after interruption.',inputSchema:{operation_id:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:true,idempotentHint:true,openWorldHint:true}},a=>run(()=>consumption.execute(a.operation_id)));
  server.registerTool('get_consumption_status',{description:'Return a saved consumption operation and fresh verification against inventory and consumption history, including exact date/reason/note. Does not submit writes.',inputSchema:{operation_id:z.string().uuid()},annotations:read},a=>run(()=>consumption.status(a.operation_id)));
  server.registerTool('get_move_status',{description:'Read the persisted operation plus fresh bottle positions. Use to reconcile interrupted or partial operations. Does not submit writes.',inputSchema:{operation_id:z.string().uuid()},annotations:read},a=>run(()=>moves.status(a.operation_id)));
  server.registerTool('search_wines',{description:'Search the global wine catalog, including wines not owned. Match producer, vintage, designation, and type before using the returned wine ID to create bottles. Page through results as needed.',inputSchema:{query:z.string().min(1).max(200),page:z.number().int().min(1).max(500).default(1)},annotations:read},a=>run(()=>searchWines(transport,a.query,a.page)));
  server.registerTool('plan_bottle_creation',{description:'Plan adding in-stock bottles to an existing catalog wine. Use a verified wine_id from search_wines. Persists a 15-minute baseline; no CellarTracker write. Size defaults to 750ml, bin to empty. Does not create a new catalog wine or record purchase costs/dates. Follow with execute_bottle_creation for authorized additions.',inputSchema:{wine_id:z.string().regex(/^\d+$/),quantity:z.number().int().min(1).max(240),location:label,size:z.string().default('750ml'),bin:label.default('')},annotations:{...read,readOnlyHint:false}},a=>run(()=>creation.plan({wineId:a.wine_id,quantity:a.quantity,location:a.location,size:a.size,bin:a.bin})));
  server.registerTool('execute_bottle_creation',{description:'Add the planned bottles and verify new inventory IDs, wine, size, location, and bin. Never replays an operation ID. After unknown/partial/running results, inspect get_creation_status; do not automatically create a replacement plan. Avoid concurrent manual additions of the same wine.',inputSchema:{operation_id:z.string().uuid()},annotations:{readOnlyHint:false,destructiveHint:false,idempotentHint:true,openWorldHint:true}},a=>run(()=>creation.execute(a.operation_id)));
  server.registerTool('get_creation_status',{description:'Read saved creation outcome and fresh new-bottle IDs compared with the original inventory baseline. Does not submit writes.',inputSchema:{operation_id:z.string().uuid()},annotations:read},a=>run(()=>creation.status(a.operation_id)));
  return server;
}
